dependencies {
    api project(":rate-limiter-api")
    implementation project(":rate-limiter-core")

    // Spring Boot auto-config + web filter
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "io.micrometer:micrometer-core"
    implementation "org.springframework:spring-web"
    implementation "jakarta.servlet:jakarta.servlet-api"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor:3.5.6"
    compileOnly "org.springframework.boot:spring-boot-configuration-processor:3.5.6"
    testImplementation platform("org.junit:junit-bom:5.8.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation "org.springframework.boot:spring-boot-test"
    testImplementation "org.springframework.boot:spring-boot-test-autoconfigure"
    testImplementation "org.springframework:spring-test"
    testImplementation "org.assertj:assertj-core"
    testImplementation "org.mockito:mockito-core"
}

test {
    useJUnitPlatform()
}
