plugins {
    id "java"
    id "maven-publish"
    id "com.vanniktech.maven.publish" version "0.36.0" apply false
}

allprojects {
    group = findProperty("MAVEN_CENTRAL_NAMESPACE") ?: "io.github.jho951"
    version = findProperty("VERSION_NAME") ?: "1.0.0-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: "java-library"
    apply plugin: "maven-publish"
    apply plugin: "com.vanniktech.maven.publish"

    java {
        toolchain { languageVersion = JavaLanguageVersion.of(17) }
        withSourcesJar()
        withJavadocJar()
    }
    dependencies {
        implementation(platform("org.springframework.boot:spring-boot-dependencies:3.5.6"))
    }

    configurations.configureEach {
        if (name.toLowerCase().startsWith("test")) {
            resolutionStrategy.force(
                "org.junit.jupiter:junit-jupiter:5.8.2",
                "org.junit.jupiter:junit-jupiter-api:5.8.2",
                "org.junit.jupiter:junit-jupiter-engine:5.8.2",
                "org.junit.jupiter:junit-jupiter-params:5.8.2",
                "org.junit.platform:junit-platform-commons:1.8.2",
                "org.junit.platform:junit-platform-engine:1.8.2",
                "org.junit.platform:junit-platform-launcher:1.8.2"
            )
        }
    }

    mavenPublishing {
        publishToMavenCentral()
        signAllPublications()
        coordinates("${project.group}", "ratelimiter-${project.name}", version)

        pom {
            name = "ratelimiter-${project.name}"
            description = "Reusable rate limiting module for Java and Spring Boot services."
            inceptionYear = "2026"
            url = "https://github.com/jho951/ratelimiter"

            licenses {
                license {
                    name = "The Apache License, Version 2.0"
                    url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                    distribution = "repo"
                }
            }

            developers {
                developer {
                    id = "jho951"
                    name = "jho951"
                    url = "https://github.com/jho951"
                }
            }

            scm {
                url = "https://github.com/jho951/ratelimiter"
                connection = "scm:git:git://github.com/jho951/ratelimiter.git"
                developerConnection = "scm:git:ssh://git@github.com/jho951/ratelimiter.git"
            }
        }
    }

    afterEvaluate {
        def plainJavadocJarTask = tasks.findByName("plainJavadocJar")
        def metadataTask = tasks.findByName("generateMetadataFileForMavenPublication")
        if (plainJavadocJarTask != null && metadataTask != null) {
            metadataTask.dependsOn(plainJavadocJarTask)
        }
    }
}
