java_version=17
junit_version=5.10.0
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
release_version=2.0.0
encoding=UTF-8
github_org=jho951
github_repo=rate-limiter
release_group=io.github.jho951
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
