rootProject.name = "rate-limiter"

include "ratelimiter-api"
project(":ratelimiter-api").projectDir = file("api")

include "ratelimiter-core"
project(":ratelimiter-core").projectDir = file("core")

include "ratelimiter-config"
project(":ratelimiter-config").projectDir = file("config")

include "ratelimiter-redis"
project(":ratelimiter-redis").projectDir = file("redis")
