name: build

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/src/**'
      - '**/*.gradle'
      - '**/*.gradle.kts'
      - 'settings.gradle'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - '**/gradle.properties'
      - 'gradle/**'
      - 'buildSrc/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - '**/src/**'
      - '**/*.gradle'
      - '**/*.gradle.kts'
      - 'settings.gradle'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - '**/gradle.properties'
      - 'gradle/**'
      - 'buildSrc/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: layer1-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_gradle.yml
    with:
      gradle-task: clean test
      timeout-minutes: 20
